# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AlosContourExtractor
                                 A QGIS plugin
 Creates contour and elevation points from Alos Palsar DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-20
        copyright            : (C) 2021 by CamellOnCase
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'CamellOnCase'
__date__ = '2021-07-20'
__copyright__ = '(C) 2021 by CamellOnCase'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import processing
from qgis.PyQt.Qt import QVariant
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsWkbTypes,
                       QgsFields,
                       QgsField,
                       QgsVectorLayer,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterBand,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterString,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingMultiStepFeedback)
from .core.handlers.raster_handler import RasterHandler
from .core.handlers.vector_handler import VectorHandler
from .core.handlers.attribute_handler import AttributeHandler
from .core.algorithms.algorithm_runner import AlgorithmRunner


class DtmContourExtractorAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    RASTER_INPUT = 'RASTER_INPUT'
    BAND_NUMBER = 'BAND_NUMBER'
    CONTOUR_INTERVAL = 'CONTOUR_INTERVAL'
    ELEVATION_ATTRIBUTE = 'ELEVATION_ATTRIBUTE'
    CONTOUR = 'CONTOUR'
    ERRORS = 'ERRORS'
    KEEP_ORIGINAL = 'KEEP_ORIGINAL'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.RASTER_INPUT,
                self.tr('Input DEM raster'),
                [QgsProcessing.TypeRaster]
            )
        )

        self.addParameter(
            QgsProcessingParameterBand(
                self.BAND_NUMBER,
                self.tr('Band number'),
                parentLayerParameterName=self.RASTER_INPUT
            )
        )
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.KEEP_ORIGINAL,
                self.tr('Keep original'),
                defaultValue=False
            )
        )
        self.addParameter(
            QgsProcessingParameterNumber(
                self.CONTOUR_INTERVAL,
                self.tr('Interval between contour lines'),
                type=0,
                defaultValue=10
            )
        )
        self.addParameter(
            QgsProcessingParameterString(
                self.ELEVATION_ATTRIBUTE,
                self.tr('Elevation attribute name'),
                defaultValue='ELEV'
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.CONTOUR,
                self.tr('Contour lines')
            )
        )
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.ERRORS,
                self.tr('Contour lines errors')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        algo_runner = AlgorithmRunner()
        vector_handler = VectorHandler()
        attribute_handler = AttributeHandler()
        multi_step_feedback = QgsProcessingMultiStepFeedback(5, feedback)
        contour_lines = QgsVectorLayer()

        input_raster_layer = self.parameterAsRasterLayer(
            parameters, self.RASTER_INPUT, context)
        input_crs = input_raster_layer.crs()
        band = self.parameterAsInt(
            parameters, self.BAND_NUMBER, context)
        keep_original = self.parameterAsBool(
            parameters, self.KEEP_ORIGINAL, context)
        interval = self.parameterAsDouble(
            parameters, self.CONTOUR_INTERVAL, context)
        elevation_attribute = self.parameterAsString(
            parameters, self.ELEVATION_ATTRIBUTE, context)

        contour_fields = attribute_handler.create_fields(
            elevation_attribute=elevation_attribute)
        errors_fields = attribute_handler.create_fields(flag=True)

        (sink, dest_id) = self.parameterAsSink(parameters,
                                               self.CONTOUR,
                                               context,
                                               contour_fields,
                                               2,
                                               input_crs)

        (errors_sink, errors_sink_id) = self.parameterAsSink(parameters,
                                                             self.ERRORS,
                                                             context,
                                                             errors_fields,
                                                             1,
                                                             input_crs)

        
        multi_step_feedback.setCurrentStep(0)
        multi_step_feedback.pushInfo(self.tr('Extracting contour lines...'))

        contour_lines = algo_runner.run_contour(input_raster_layer,
                                            band,
                                            elevation_attribute,
                                            interval,
                                            context, feedback)

        if keep_original:
            features = contour_lines.getFeatures()
            sink.addFeatures(features, QgsFeatureSink.FastInsert)

            return {self.CONTOUR: dest_id}
        
        multi_step_feedback.setCurrentStep(1)
        simplified_contour = vector_handler.retrieve_simplified_smoothed_contour(
            contour_lines, context, multi_step_feedback)

        multi_step_feedback.setCurrentStep(2)
        multi_step_feedback.pushInfo(self.tr('\n Retrieving intersected contour lines...'))
        errors = list()
        intersection_points = algo_runner.run_line_intersections(
            simplified_contour, context, feedback)
        errors.extend(intersection_points.getFeatures())

        multi_step_feedback.setCurrentStep(3)
        multi_step_feedback.pushInfo(self.tr('\n Retrieving colapsed contour lines...'))
        for feature in simplified_contour.getFeatures():
            colapsed_points = vector_handler.get_out_of_bounds_angle(
                feature.geometry(), 10)
            errors.extend(colapsed_points)

        multi_step_feedback.setCurrentStep(4)
        multi_step_feedback.pushInfo(self.tr('Filtering contour lines...\n'))
        filtered_features = vector_handler.filter_geometry_by_length(simplified_contour)

        features = filtered_features.getFeatures()
        sink.addFeatures(features, QgsFeatureSink.FastInsert)

        errors_sink.addFeatures(errors, QgsFeatureSink.FastInsert)

        return {self.CONTOUR: dest_id,
                self.ERRORS: errors_sink_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'contourextractor'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Contour Extractor')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Contour Tools'

    def shortHelpString(self):
        """
        Retruns a short helper string for the algorithm
        """
        return self.tr("""extracts the contours""")

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DtmContourExtractorAlgorithm()
