# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AlosContourExtractor
                                 A QGIS plugin
 Creates contour and elevation points from Alos Palsar DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-20
        copyright            : (C) 2021 by CamellOnCase
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francisco Alves Camello Neto'
__date__ = '2021-07-30'
__copyright__ = '(C) 2021 by CamellOnCase'

from qgis.analysis import QgsGeometrySnapper, QgsInternalGeometrySnapper
from qgis.core import (edit, Qgis, QgsFields, QgsCoordinateReferenceSystem, QgsCoordinateTransform,
                       QgsExpression, QgsFeature, QgsFeatureRequest, QgsField, QgsGeometry, QgsMessageLog,
                       QgsProcessingContext, QgsProcessingMultiStepFeedback, QgsProcessingUtils, QgsProject,
                       QgsSpatialIndex, QgsVectorDataProvider, QgsVectorLayer, QgsVectorLayerUtils, QgsWkbTypes,
                       QgsProcessingFeatureSourceDefinition, QgsFeatureSink)
from qgis.PyQt.Qt import QObject, QVariant
from ..algorithms.algorithm_runner import AlgorithmRunner


class AttributeHandler(QObject):
    """
    Docstring
    """

    def __init__(self, iface=None, parent=None):
        super(AttributeHandler, self).__init__()
        self.parent = parent
        self.iface = iface
        if iface:
            self.canvas = iface.mapCanvas()
        self.algorithm_runner = AlgorithmRunner()

    @staticmethod
    def set_attribute_value(feature, field_name, field_value):
        feature[field_name] = field_value

        return feature

    @staticmethod
    def create_fields(elevation_attribute=None, error=False):
        """
        Docstring
        """
        fields_map = QgsFields()

        if error:
            # fields_map.append(QgsField('id', QVariant.Int))
            fields_map.append(QgsField('check', QVariant.String))
            return fields_map

        fields_map.append(QgsField('id', QVariant.Int))
        fields_map.append(QgsField(elevation_attribute, QVariant.Double))

        return fields_map

    @staticmethod
    def delete_fields(input_layer, field_list):
        """
        Docstring
        :return: (QgsRectangle) raster bounding box
        """
        provider = input_layer.dataProvider()
        field_idx_list = list()
        fields = input_layer.fields()

        for field in fields:
            if field.name() in field_list:
                field_idx = provider.fieldNameIndex(field.name())
                field_idx_list.append(field_idx)

        provider.deleteAttributes(field_idx_list)
        input_layer.updateFields()

        return input_layer

